AllCops:
  Exclude:
    - db/migrate/**
    - db/schema.rb
    - node_modules/**/*
    - bin/*
    - public/**/*

Layout/EndOfLine:
  EnforcedStyle: lf

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20
